### ISSUE TITLE
noscript Enable Javascript... but it's enabled!

### ISSUE THREAD

**Issue by fglaria** [fglaria/sitamco#11]
On client, opening console, on Elements you can se inside body before root div
`<noscript>You need to enable JavaScript to run this app.</noscript>`

**Comment by juboba** [comment]
![image](https://user-images.githubusercontent.com/1189739/104822601-1055a200-5844-11eb-85be-a84021558b78.png)

If this is what you mean, this is a message to show the browsers that have javascript disabled (that's why it's in plain text and not provided by any function).

### This way, if somebody has some addon to disable javascript or they have it disabled in the browser:
![image](https://user-images.githubusercontent.com/1189739/104822629-50b52000-5844-11eb-8bba-6b6e0bffd7f2.png)

### They would see the message:
![image](https://user-images.githubusercontent.com/1189739/104822638-5a3e8800-5844-11eb-86bd-baf7f0180ab8.png)

**Comment by fglaria** [comment]
I knew this was the reason, but I think it's dumber not to ask a dumb question than to do so.
